services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: mototrack
      POSTGRES_USER: mototrack
      POSTGRES_PASSWORD: mototrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mototrack -d mototrack"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
